"use client";

import React from 'react';
import { useAppStore } from '../store/useAppStore';
import { motion } from 'motion/react';
import { CheckCircle2, AlertTriangle, Lightbulb, FileText, RefreshCw } from 'lucide-react';
import { ExportPDFButton } from './ExportPDFButton';

export function AnalysisPanel() {
  const { conversation, reset } = useAppStore();
  const { analysis, problemStatement, steps } = conversation;

  if (!analysis) return null;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full max-w-4xl mx-auto space-y-4 sm:space-y-8"
      id="analysis-report"
    >
      <div className="bg-white dark:bg-white/5 p-4 sm:p-8 md:p-12 rounded-xl sm:rounded-2xl shadow-sm border border-slate-200 dark:border-white/10 print-break-inside-avoid">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 sm:mb-12 pb-6 border-b border-slate-100 dark:border-white/5 gap-4 sm:gap-6">
          <div className="space-y-1">
            <h2 className="text-lg sm:text-2xl md:text-3xl font-bold text-slate-900 dark:text-white tracking-tight leading-tight">
              Root Cause Analysis Report
            </h2>
            <p className="text-slate-500 dark:text-slate-400 text-xs sm:text-sm md:text-base">Generated by 5 Whys Diagnostic System</p>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 sm:px-4 sm:py-2 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 rounded-full font-semibold border border-emerald-100 dark:border-emerald-900/30 self-start md:self-center text-xs sm:text-sm md:text-base">
            <CheckCircle2 className="w-3.5 h-3.5 sm:w-5 sm:h-5" />
            Confidence: {analysis.confidence}%
          </div>
        </div>

        <div className="space-y-8 sm:space-y-12">
          <section className="print-break-inside-avoid">
            <h3 className="text-xs sm:text-sm md:text-base font-bold text-slate-400 dark:text-slate-500 mb-3 sm:mb-4 flex items-center gap-2 uppercase tracking-widest">
              <AlertTriangle className="w-4 h-4 text-amber-500" />
              Identified Root Cause
            </h3>
            <div className="p-4 sm:p-8 bg-amber-50/30 dark:bg-amber-900/10 rounded-xl sm:rounded-2xl border border-amber-100/50 dark:border-amber-900/20">
              <p className="text-sm sm:text-lg md:text-xl text-slate-800 dark:text-slate-200 font-medium leading-relaxed">
                {analysis.rootCause}
              </p>
            </div>
          </section>

          <section className="print-break-inside-avoid">
            <h3 className="text-xs sm:text-sm md:text-base font-bold text-slate-400 dark:text-slate-500 mb-3 sm:mb-4 flex items-center gap-2 uppercase tracking-widest">
              <FileText className="w-4 h-4 text-blue-500" />
              Detailed Explanation
            </h3>
            <div className="prose prose-slate dark:prose-invert max-w-none">
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-xs sm:text-base md:text-lg">
                {analysis.explanation}
              </p>
            </div>
          </section>

          <section className="print-break-inside-avoid">
            <h3 className="text-xs sm:text-sm md:text-base font-bold text-slate-400 dark:text-slate-500 mb-3 sm:mb-4 flex items-center gap-2 uppercase tracking-widest">
              <Lightbulb className="w-4 h-4 text-indigo-500" />
              Recommended Actions
            </h3>
            <div className="grid gap-2 sm:gap-4">
              {analysis.recommendations.map((rec, index) => (
                <div key={index} className="flex items-start gap-3 sm:gap-4 p-3 sm:p-6 bg-slate-50/50 dark:bg-white/5 rounded-xl sm:rounded-2xl border border-slate-200 dark:border-white/10 print-break-inside-avoid">
                  <span className="flex items-center justify-center w-6 h-6 sm:w-8 sm:h-8 rounded-full bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-400 font-bold text-[10px] sm:text-sm shrink-0">
                    {index + 1}
                  </span>
                  <span className="text-slate-700 dark:text-slate-300 text-xs sm:text-base leading-relaxed pt-0.5">{rec}</span>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>

      <div className="bg-white dark:bg-white/5 p-4 sm:p-8 md:p-12 rounded-xl sm:rounded-2xl shadow-sm border border-slate-200 dark:border-white/10 print-break-before-page">
        <div className="mb-6 sm:mb-10 pb-6 border-b border-slate-100 dark:border-white/5">
          <h3 className="text-lg sm:text-2xl font-bold text-slate-900 dark:text-white tracking-tight">Investigation Timeline</h3>
        </div>
        
        <div className="space-y-6 sm:space-y-8">
          <div className="p-4 sm:p-8 bg-slate-50/50 dark:bg-white/5 rounded-xl sm:rounded-2xl border border-slate-200 dark:border-white/10 print-break-inside-avoid">
            <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-2 block">Initial Problem Statement</span>
            <p className="text-sm sm:text-xl text-slate-900 dark:text-white font-medium leading-tight">{problemStatement}</p>
          </div>

          <div className="space-y-6 sm:space-y-8 pl-3 sm:pl-8 border-l-2 border-indigo-100 dark:border-indigo-900/30 ml-1 sm:ml-2">
            {steps.map((step, index) => (
              <div key={index} className="relative pl-5 sm:pl-10 print-break-inside-avoid">
                <div className="absolute -left-[21px] sm:-left-[41px] top-1 w-3 h-3 sm:w-5 sm:h-5 rounded-full bg-white dark:bg-[#0a0a0a] border-2 sm:border-4 border-indigo-500" />
                <div className="space-y-2 sm:space-y-3">
                  <p className="text-[10px] font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-widest">Why {step.level}</p>
                  <p className="text-sm sm:text-lg font-semibold text-slate-900 dark:text-white leading-snug">{step.question}</p>
                  <div className="bg-slate-50/50 dark:bg-white/5 p-3 sm:p-5 rounded-xl sm:rounded-2xl border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 text-xs sm:text-base leading-relaxed">
                    {step.answer}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-10 sm:mt-16 pt-8 border-t border-slate-100 dark:border-white/5 flex flex-col sm:flex-row justify-between items-center gap-4 text-[10px] text-slate-300 dark:text-slate-600 uppercase tracking-widest font-bold text-center sm:text-left">
          <span>5 Whys Diagnostic Report</span>
          <span>Confidential & Internal Use Only</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-end gap-4 pt-4 no-print">
        <button
          onClick={reset}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-white/5 rounded-xl font-medium transition-colors"
        >
          <RefreshCw className="w-5 h-5" />
          Start New Analysis
        </button>
        <div className="w-full sm:w-auto">
          <ExportPDFButton />
        </div>
      </div>
    </motion.div>
  );
}
